working_directory = "C:\\Users\\jungl\\dev"

import = [
#    "~/.config/alacritty/themes/themes/"
]

[colors.cursor]
cursor = "#ffdd33"
text = "#000000"
[cursor.style]
blinking = "Always"

[font]
size = 24
normal = { family = "Iosevka Nerd Font Mono" }

[window]
startup_mode = "Maximized"
