working_directory = "C:\\Users\\shatto"

import = [
#    "~/.config/alacritty/themes/themes/"
]

[colors.primary]
background = "#0b0b0b"

[colors.cursor]
cursor = "#00ee00"
text = "#000000"
[cursor.style]
blinking = "Always"

[font]
size = 14
normal = { family = "Consolas" }

[window]
startup_mode = "Maximized"

[shell]
program = "cmd"
